-- SQL Script to Insert 10 Sample Leads into contact_submissions table
-- Run this script in your Supabase SQL Editor to populate the leads table

INSERT INTO public.contact_submissions (
  first_name,
  last_name,
  email,
  phone,
  company,
  job_title,
  website,
  company_size,
  industry,
  project_description,
  timeline,
  budget_range,
  urgency,
  preferred_contact_method,
  best_time_to_call,
  meeting_type,
  additional_notes,
  country,
  city,
  state,
  lead_status,
  lead_score,
  captcha_verified,
  created_at,
  updated_at
) VALUES 
-- Lead 1: Rahimullah Haqyar
(
  'Rahimullah',
  'Haqyar',
  'rahimullah.haqyar@techcorp.pk',
  '+923125365377',
  'TechCorp Solutions',
  'CEO',
  'www.techcorp.pk',
  '50-200',
  'Technology',
  'Looking for AI-driven business intelligence solutions to optimize our operations and improve decision-making processes.',
  '3-6 months',
  '$50,000 - $100,000',
  'medium',
  'email',
  'morning',
  'video_call',
  'Interested in predictive analytics for customer behavior',
  'Pakistan',
  'Karachi',
  'Sindh',
  'contacted',
  75,
  true,
  '2025-01-28 10:30:00+00',
  '2025-01-28 10:30:00+00'
),

-- Lead 2: Nasir Iqbal
(
  'Nasir',
  'Iqbal',
  'nasir.iqbal@innovatetech.com',
  '+46700376549',
  'InnovateTech AB',
  'CTO',
  'www.innovatetech.se',
  '200-500',
  'Software Development',
  'Need machine learning integration for our existing software platform to enhance user experience.',
  '6-12 months',
  '$100,000 - $250,000',
  'high',
  'phone',
  'afternoon',
  'in_person',
  'Previous experience with ML projects, looking for advanced solutions',
  'Sweden',
  'Stockholm',
  'Stockholm County',
  'contacted',
  85,
  true,
  '2025-01-27 14:15:00+00',
  '2025-01-27 14:15:00+00'
),

-- Lead 3: Fahad Saeed
(
  'Fahad',
  'Saeed',
  'fahad.saeed@globalfinance.ae',
  '+03115841449',
  'Global Finance Group',
  'Head of Operations',
  'www.globalfinance.ae',
  '500-1000',
  'Financial Services',
  'Seeking automated risk assessment and compliance management solutions for our financial operations.',
  '1-3 months',
  '$250,000 - $500,000',
  'high',
  'email',
  'evening',
  'video_call',
  'Urgent project due to regulatory requirements',
  'UAE',
  'Dubai',
  'Dubai',
  'contacted',
  90,
  true,
  '2025-01-26 16:45:00+00',
  '2025-01-26 16:45:00+00'
),

-- Lead 4: Zeeshan Raza
(
  'Zeeshan',
  'Raza',
  'zeeshan.raza@healthtech.com',
  '+923004448483',
  'HealthTech Innovations',
  'Product Manager',
  'www.healthtech.com',
  '100-500',
  'Healthcare',
  'Looking for AI-powered patient data analysis and predictive healthcare solutions.',
  '6-12 months',
  '$75,000 - $150,000',
  'medium',
  'phone',
  'morning',
  'video_call',
  'Focus on HIPAA compliance and data security',
  'Pakistan',
  'Lahore',
  'Punjab',
  'contacted',
  80,
  true,
  '2025-01-26 09:20:00+00',
  '2025-01-26 09:20:00+00'
),

-- Lead 5: Asad Zulfiqar
(
  'Asad',
  'Zulfiqar',
  'asad.zulfiqar@retailpro.com',
  '+4368181923978',
  'RetailPro Analytics',
  'Data Science Director',
  'www.retailpro.com',
  '1000+',
  'Retail',
  'Need comprehensive business intelligence dashboard and customer analytics platform.',
  '3-6 months',
  '$150,000 - $300,000',
  'low',
  'email',
  'afternoon',
  'in_person',
  'Large scale implementation across multiple locations',
  'Austria',
  'Vienna',
  'Vienna',
  'contacted',
  70,
  true,
  '2025-01-26 11:10:00+00',
  '2025-01-26 11:10:00+00'
),

-- Lead 6: Sarah Johnson
(
  'Sarah',
  'Johnson',
  'sarah.johnson@manufacturingplus.com',
  '+14155552345',
  'Manufacturing Plus Inc',
  'Operations Director',
  'www.manufacturingplus.com',
  '200-500',
  'Manufacturing',
  'Interested in process automation and predictive maintenance solutions for our production line.',
  '1-3 months',
  '$100,000 - $200,000',
  'high',
  'phone',
  'morning',
  'video_call',
  'Looking to reduce downtime and improve efficiency',
  'United States',
  'San Francisco',
  'California',
  'new',
  65,
  true,
  '2025-01-25 15:30:00+00',
  '2025-01-25 15:30:00+00'
),

-- Lead 7: Ahmed Al-Rashid
(
  'Ahmed',
  'Al-Rashid',
  'ahmed.alrashid@smartcity.sa',
  '+966501234567',
  'Smart City Solutions',
  'Project Manager',
  'www.smartcity.sa',
  '50-200',
  'Government',
  'Developing smart city infrastructure with IoT and AI integration for traffic management.',
  '12+ months',
  '$500,000+',
  'medium',
  'email',
  'afternoon',
  'in_person',
  'Government project with multiple phases',
  'Saudi Arabia',
  'Riyadh',
  'Riyadh Province',
  'qualified',
  88,
  true,
  '2025-01-24 13:45:00+00',
  '2025-01-24 13:45:00+00'
),

-- Lead 8: Maria Rodriguez
(
  'Maria',
  'Rodriguez',
  'maria.rodriguez@edutech.es',
  '+34612345678',
  'EduTech Innovations',
  'Head of Technology',
  'www.edutech.es',
  '100-500',
  'Education',
  'Need AI-powered learning analytics and personalized education platform development.',
  '6-12 months',
  '$75,000 - $150,000',
  'low',
  'email',
  'morning',
  'video_call',
  'Focus on student performance analytics',
  'Spain',
  'Madrid',
  'Madrid',
  'new',
  60,
  true,
  '2025-01-23 10:15:00+00',
  '2025-01-23 10:15:00+00'
),

-- Lead 9: David Chen
(
  'David',
  'Chen',
  'david.chen@logisticsai.com',
  '+8613812345678',
  'Logistics AI Solutions',
  'VP of Innovation',
  'www.logisticsai.com',
  '500-1000',
  'Logistics',
  'Looking for supply chain optimization and route planning AI solutions.',
  '3-6 months',
  '$200,000 - $400,000',
  'high',
  'phone',
  'evening',
  'video_call',
  'International shipping optimization focus',
  'China',
  'Shanghai',
  'Shanghai',
  'converted',
  95,
  true,
  '2025-01-22 08:30:00+00',
  '2025-01-22 08:30:00+00'
),

-- Lead 10: Jennifer Smith
(
  'Jennifer',
  'Smith',
  'jennifer.smith@realestatetech.com',
  '+14165551234',
  'RealEstate Tech Corp',
  'Chief Innovation Officer',
  'www.realestatetech.com',
  '200-500',
  'Real Estate',
  'Interested in property valuation AI and market analysis tools for real estate investment.',
  '1-3 months',
  '$50,000 - $100,000',
  'medium',
  'email',
  'afternoon',
  'in_person',
  'Focus on predictive market trends',
  'Canada',
  'Toronto',
  'Ontario',
  'qualified',
  78,
  true,
  '2025-01-21 12:00:00+00',
  '2025-01-21 12:00:00+00'
);

-- Note: The 'name' field is computed dynamically in the frontend from first_name + last_name
-- No need to update a 'name' column as it doesn't exist in the database schema

-- Verify the data insertion
SELECT 
  CONCAT(first_name, ' ', last_name) as name,
  email,
  phone,
  company,
  country,
  lead_status,
  urgency,
  budget_range,
  created_at
FROM public.contact_submissions 
ORDER BY created_at DESC
LIMIT 10;